### ISSUE TITLE
Unexpected list instead of dict during LoadStage

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-lib-data-ingest#629]
While running an ingest, @Christina-J-Diaz encountered the following error:
```
2021-08-18 16:31:03,910 - GuidedTransformStage - Thread: MainThread - INFO - ❌ TransformStage failed validation!
2021-08-18 16:31:03,910 - GuidedTransformStage - Thread: MainThread - INFO - END GuidedTransformStage. Time elapsed: Sec: 0.9110019207000732 Min: 0.0 Hours: 0.0
2021-08-18 16:31:03,920 - LoadStage - Thread: MainThread - INFO - Loader Version: 2
2021-08-18 16:31:03,920 - LoadStage - Thread: MainThread - INFO - BEGIN LoadStage
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of investigator. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of study. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of family. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of participant. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of family_relationship. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of diagnosis. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of phenotype. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of outcome. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of biospecimen. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of genomic_file. Not included in ingest package config.
2021-08-18 16:31:03,921 - LoadStage - Thread: MainThread - INFO - Skipping load of read_group. Not included in ingest package config.
2021-08-18 16:31:03,922 - LoadStage - Thread: MainThread - INFO - Begin loading sequencing_experiment
2021-08-18 16:31:03,991 - LoadStage - Thread: MainThread - INFO - Reading 7800 rows in 'default' table.
2021-08-18 16:31:05,540 - DataIngestPipeline - Thread: MainThread - ERROR - list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/ingest_pipeline.py", line 274, in run
    output = stage.run(
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/common/stage.py", line 148, in wrapper
    r = func(instance, *args, **kwargs)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/common/stage.py", line 173, in run
    output = self._run(*args, **kwargs)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load_base.py", line 411, in _run
    self._load_entity(entity_class, record)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load_base.py", line 315, in _load_entity
    target_id = self._do_target_submit(entity_class, body)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load_v2.py", line 83, in _do_target_submit
    return entity_class.submit(self.target_url, body)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py", line 618, in submit
    return submit(host, cls, body)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py", line 990, in submit
    return result["kf_id"]
TypeError: list indices must be integers or slices, not str
2021-08-18 16:31:05,542 - DataIngestPipeline - Thread: MainThread - ERROR - ❌ Ingest pipeline did not complete execution! See /Users/diazcj/SD_VTTSHWV4/sequencing_experiment/logs/ingest.log for details
```

When `kidsfirst ingest` is run, the output from the LoadStage is `[]`. But, when `kidsfirst test` is run, this doesn't happen. It seems that `result` in the `submit` function of `kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py` is a list, when a dict is expected.

**Comment by gsantia** [comment]
Closing as part of #630

**Comment by chris-s-friedman** [comment]
per @Christina-J-Diaz in #630: 

>While on the VPN I tried ingesting using kidsfirst ingest -t http://kf-api-dataservice.kidsfirstdrc.org sequencing_experiment and got the error above. I noticed that the json output from the load stage was []. But this wasn't the case when I ran kidsfirst test or kidsfirst ingest -t http://kf-api-dataservice.kidsfirstdrc.org --dry_run. I decided to go off the VPN and try tunneling into prd to see if the same issue happened. Instead of a list indices error I got a WARNING message:

    Thread: MainThread - WARNING - Retrying (Retry(total=9, connect=10, read=9, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /sequencing-experiments?limit=100&study_id=SD_VTTSHWV4&sequencing_center_id=SC_X1N69WJM&external_id=SL334354

> So I went back and carefully read the command I was using (specifically the target url). I noticed I was using http:// instead of https://...once I made the change I had no problem loading.

**Comment by chris-s-friedman** [comment]
If I understand the jist of this correctly, we need to have a better way to report the failure to connect during the loadstage?

**Comment by fiendish** [comment]
I think we need to ask why the request got back a status code of 200/201 per the condition around that return.

**Comment by gsantia** [comment]
> I think we need to ask why the request got back a status code of 200/201 per the condition around that return. But we can definitely improve robustness by looking at the response body and making sure that it looks like a real result instead of just assuming it has a kfid entry. Anyone want to amend the contents of
> 
> https://github.com/kids-first/kf-lib-data-ingest/blob/48b4bc8a3226afe7624d13d3bd00072034ed3e3b/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py#L988-L990
> 
> while I'm out to raise another request exception if the response is bad despite a good status?

sure got it
