### ISSUE TITLE
[Discussion] should the ingest library detect if a target api is using http instead of https

### ISSUE THREAD

**Issue by chris-s-friedman** [kids-first/kf-lib-data-ingest#630]
setting target api to `http://kf-api-dataservice.kidsfirstdrc.org` instead `https...` breaks the load stage of the ingest library and returns: 
```
2021-08-18 16:31:05,540 - DataIngestPipeline - Thread: MainThread - ERROR - list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/ingest_pipeline.py", line 274, in run
    output = stage.run(
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/common/stage.py", line 148, in wrapper
    r = func(instance, *args, **kwargs)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/common/stage.py", line 173, in run
    output = self._run(*args, **kwargs)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load_base.py", line 411, in _run
    self._load_entity(entity_class, record)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load_base.py", line 315, in _load_entity
    target_id = self._do_target_submit(entity_class, body)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/etl/load/load_v2.py", line 83, in _do_target_submit
    return entity_class.submit(self.target_url, body)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py", line 618, in submit
    return submit(host, cls, body)
  File "/Users/diazcj/venv/lib/python3.8/site-packages/kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py", line 990, in submit
    return result["kf_id"]
TypeError: list indices must be integers or slices, not str
2021-08-18 16:31:05,542 - DataIngestPipeline - Thread: MainThread - ERROR - ❌ Ingest pipeline did not complete execution! See /Users/diazcj/SD_VTTSHWV4/sequencing_experiment/logs/ingest.log for details
```

@Christina-J-Diaz please add details below of how and why you found this issue.

**Comment by Christina-J-Diaz** [comment]
While on the VPN I tried ingesting using `kidsfirst ingest -t http://kf-api-dataservice.kidsfirstdrc.org sequencing_experiment` and got the error above. I noticed that the json output from the load stage was `[]`. But this wasn't the case when I ran `kidsfirst test` or `kidsfirst ingest -t http://kf-api-dataservice.kidsfirstdrc.org  --dry_run`. I decided to go off the VPN and try tunneling into prd to see if the same issue happened. Instead of a list indices error I got a WARNING message: 

> Thread: MainThread - WARNING - Retrying (Retry(total=9, connect=10, read=9, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /sequencing-experiments?limit=100&study_id=SD_VTTSHWV4&sequencing_center_id=SC_X1N69WJM&external_id=SL334354

So I went back and carefully read the command I was using (specifically the target url). I noticed I was using `http://` instead of `https://`...once I made the change I had no problem loading.

**Comment by fiendish** [comment]
> should the ingest library detect if a target api is using http instead of https

That seems quite out of scope. I'm in favor of merging the details from this issue into #629, closing this and reopening that.

**Comment by chris-s-friedman** [comment]
agreed re: 
> That seems quite out of scope... choosing the right URL seems like it should stay a user decision.

> We can do better about reporting the failure mechanism

> merging the details from this issue into #629 

I'll close this issue and reopen #630.
